export const ALIAS_WORDS: readonly string[] = [
  'castle', 'pillow', 'volcano', 'doctor', 'ladder', 'ocean', 'guitar', 'shadow', 'candle', 'elephant',
  'mirror', 'thunder', 'kitchen', 'umbrella', 'dragon', 'bicycle', 'forest', 'lantern', 'crown', 'submarine',
  'library', 'compass', 'tornado', 'bakery', 'telescope', 'pyramid', 'whistle', 'cactus', 'hammock', 'glacier',
  'chimney', 'magnet', 'sandbox', 'lighthouse', 'pretzel', 'trapeze', 'carousel', 'anchor', 'balloon', 'treasure',
  'penguin', 'suitcase', 'shovel', 'rainbow', 'campfire', 'parachute', 'hourglass', 'blanket', 'bridge', 'statue',
  'canyon', 'riddle', 'sunrise', 'snowflake', 'meadow', 'corkscrew', 'waterfall', 'diamond', 'feather', 'cabinet',
  'clocktower', 'stallion', 'coconut', 'jungle', 'podium', 'sponge', 'mustache', 'trophy', 'caterpillar', 'puzzle',
  'noodle', 'doorbell', 'bracelet', 'lemon', 'knitting', 'seagull', 'blizzard', 'moonlight', 'cinnamon', 'staircase',
  'snowman', 'whisper', 'curtain', 'dolphin', 'keyboard', 'giraffe', 'teapot', 'scarecrow', 'unicorn', 'thunderstorm',
  'carnival', 'bulldozer', 'passport', 'skeleton', 'hurricane', 'labyrinth', 'octopus', 'footprint', 'spaghetti', 'windmill',
  'calendar', 'jellyfish', 'cathedral', 'fireworks', 'porcupine', 'avalanche', 'breakfast', 'honeybee', 'starfish', 'marathon',
  'armadillo', 'trapdoor', 'quicksand', 'pendulum', 'envelope', 'shipwreck', 'astronaut', 'cannonball', 'crocodile', 'popcorn',
  'fireplace', 'mushroom', 'stalactite', 'thunderbolt', 'xylophone', 'satellite', 'magician', 'doorstep', 'igloo', 'tapestry',
  'sandstorm', 'helicopter', 'periscope', 'driftwood', 'mongoose', 'accordion', 'cobblestone', 'firefly', 'chandelier', 'pebble',
  'sparrow', 'tangerine', 'centipede', 'stethoscope', 'birdsong', 'cobweb', 'snowdrift', 'binoculars', 'toothbrush', 'doorknob',
  'pineapple', 'stargazer', 'quill', 'raindrop', 'lifeboat', 'catapult', 'windchime', 'lollipop', 'backpack', 'sandals',
  'typewriter', 'harmonica', 'jellybean', 'pinecone', 'watermelon', 'strawberry', 'paintbrush', 'signpost', 'earthquake', 'chalkboard',
  'tambourine', 'macaroon', 'daffodil', 'whirlpool', 'flamingo', 'scorpion', 'trombone', 'footstool', 'keystone', 'marshmallow',
  'pomegranate', 'boomerang', 'catfish', 'goblin', 'sandpaper', 'clockwork', 'starship', 'moonbeam', 'toadstool', 'butterscotch',
  'archipelago', 'kaleidoscope', 'bubblegum', 'dragonfly', 'glowworm', 'thundercloud', 'tadpole', 'mudslide', 'candlestick', 'patchwork',
] as const
