pre-commit:
  parallel: false
  commands:
    boardly-pre-commit:
      run: node --import tsx scripts/git-hook-pre-commit.ts

commit-msg:
  commands:
    boardly-commit-msg:
      run: node --import tsx scripts/git-hook-commit-msg.ts {1}

pre-push:
  parallel: false
  commands:
    boardly-pre-push:
      run: node --import tsx scripts/git-hook-pre-push.ts
