import { prisma } from '@/lib/db'
import { logger } from '@/lib/logger'
import {
  evaluateReliabilityAlerts,
  type ReliabilityAlertEvaluation,
  type ReliabilityAlertRuleStatus,
} from '@/lib/operational-metrics'

export interface ReliabilityAlertCycleOptions {
  windowMinutes?: number
  baselineDays?: number
  repeatMinutes?: number
  webhookUrl?: string
  runbookBaseUrl?: string
  githubToken?: string
  githubRepo?: string
  dryRun?: boolean
}

export interface ReliabilityAlertCycleResult {
  evaluation: ReliabilityAlertEvaluation
  triggered: ReliabilityAlertRuleStatus[]
  resolved: ReliabilityAlertRuleStatus[]
  notificationsSent: number
  dryRun: boolean
}

function isMissingOperationalAlertStatesTableError(error: unknown): boolean {
  if (!error || typeof error !== 'object') return false
  if (!('code' in error) || (error as { code?: unknown }).code !== 'P2021') return false

  const meta = (error as { meta?: { table?: unknown } }).meta
  return typeof meta?.table === 'string' && meta.table.includes('OperationalAlertStates')
}

function shouldNotifyAgain(lastNotifiedAt: Date | null, repeatMinutes: number): boolean {
  if (!lastNotifiedAt) return true
  return Date.now() - lastNotifiedAt.getTime() >= repeatMinutes * 60 * 1000
}

function buildRunbookUrl(path: string, runbookBaseUrl?: string): string {
  if (!runbookBaseUrl) return path
  try {
    return new URL(path, runbookBaseUrl).toString()
  } catch {
    return path
  }
}

function formatValue(rule: ReliabilityAlertRuleStatus): string {
  return typeof rule.currentValue === 'number' && Number.isFinite(rule.currentValue)
    ? `${rule.currentValue.toFixed(2)} ${rule.unit}`
    : `n/a ${rule.unit}`
}

// ─── GitHub API ────────────────────────────────────────────────────────────

const GH_API = 'https://api.github.com'

async function githubRequest(
  method: string,
  path: string,
  token: string,
  body?: unknown
): Promise<{ ok: boolean; data: unknown }> {
  const res = await fetch(`${GH_API}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  })
  const data = await res.json().catch(() => ({}))
  return { ok: res.ok, data }
}

async function createGitHubIssue(params: {
  token: string
  repo: string
  rule: ReliabilityAlertRuleStatus
  runbookBaseUrl?: string
  triggeredAt: string
}): Promise<number | null> {
  const { token, repo, rule, runbookBaseUrl, triggeredAt } = params
  const runbook = buildRunbookUrl(rule.runbookPath, runbookBaseUrl)

  const title = `[ALERT] ${rule.alertKey} — ${rule.summary}`
  const body = [
    `## Reliability Alert: \`${rule.alertKey}\``,
    '',
    `| Field | Value |`,
    `|---|---|`,
    `| **Severity** | ${rule.severity} |`,
    `| **Current value** | ${formatValue(rule)} |`,
    `| **Threshold** | ${rule.thresholdValue} ${rule.unit} |`,
    `| **Window** | ${rule.windowMinutes} min |`,
    `| **Triggered at** | ${triggeredAt} |`,
    '',
    `**Summary:** ${rule.summary}`,
    '',
    `**Runbook:** ${runbook}`,
    '',
    `---`,
    `*Auto-generated by Boardly reliability monitor. This issue will be closed automatically when the alert resolves.*`,
  ].join('\n')

  const { ok, data } = await githubRequest('POST', `/repos/${repo}/issues`, token, {
    title,
    body,
    labels: ['alert', 'bug'],
  })

  if (!ok || typeof (data as { number?: unknown }).number !== 'number') {
    logger.error('Failed to create GitHub issue for alert', { alertKey: rule.alertKey, data })
    return null
  }

  return (data as { number: number }).number
}

async function closeGitHubIssue(params: {
  token: string
  repo: string
  issueNumber: number
  rule: ReliabilityAlertRuleStatus
  resolvedAt: string
}): Promise<void> {
  const { token, repo, issueNumber, rule, resolvedAt } = params

  const comment = [
    `## ✅ Alert Resolved`,
    '',
    `| Field | Value |`,
    `|---|---|`,
    `| **Resolved at** | ${resolvedAt} |`,
    `| **Final value** | ${formatValue(rule)} |`,
    `| **Threshold** | ${rule.thresholdValue} ${rule.unit} |`,
    '',
    `*Value returned to normal. Closing automatically.*`,
  ].join('\n')

  await githubRequest('POST', `/repos/${repo}/issues/${issueNumber}/comments`, token, {
    body: comment,
  })

  await githubRequest('PATCH', `/repos/${repo}/issues/${issueNumber}`, token, {
    state: 'closed',
    state_reason: 'completed',
  })
}

// ─── Discord embeds ─────────────────────────────────────────────────────────

const EMBED_COLORS = {
  critical_triggered: 15548997, // #ED4245 red
  warning_triggered:  16776960, // #FFFF00 yellow
  resolved:           5763719,  // #57F287 green
} as const

function buildDiscordEmbed(params: {
  status: 'TRIGGERED' | 'RESOLVED'
  rule: ReliabilityAlertRuleStatus
  runbookBaseUrl?: string
  generatedAt: string
  githubIssueNumber?: number | null
  githubRepo?: string
}): object {
  const { status, rule, runbookBaseUrl, generatedAt, githubIssueNumber, githubRepo } = params
  const runbook = buildRunbookUrl(rule.runbookPath, runbookBaseUrl)

  const colorKey =
    status === 'RESOLVED'
      ? 'resolved'
      : rule.severity === 'critical'
        ? 'critical_triggered'
        : 'warning_triggered'

  const statusEmoji = status === 'RESOLVED' ? '🟢' : rule.severity === 'critical' ? '🔴' : '🟡'

  const fields: Array<{ name: string; value: string; inline?: boolean }> = [
    { name: 'Severity',   value: rule.severity,                    inline: true },
    { name: 'Value',      value: formatValue(rule),                inline: true },
    { name: 'Threshold',  value: `${rule.thresholdValue} ${rule.unit}`, inline: true },
    { name: 'Window',     value: `${rule.windowMinutes} min`,      inline: true },
    { name: 'Summary',    value: rule.summary },
    { name: 'Runbook',    value: runbook },
  ]

  if (githubIssueNumber && githubRepo) {
    const url = `https://github.com/${githubRepo}/issues/${githubIssueNumber}`
    fields.push({ name: 'GitHub Issue', value: `[#${githubIssueNumber}](${url})` })
  }

  return {
    embeds: [
      {
        title: `${statusEmoji} [${status}] ${rule.alertKey}`,
        color: EMBED_COLORS[colorKey],
        fields,
        timestamp: generatedAt,
      },
    ],
  }
}

async function sendDiscordEmbed(webhookUrl: string, payload: object): Promise<void> {
  const response = await fetch(webhookUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  })

  if (!response.ok) {
    const text = await response.text().catch(() => '')
    throw new Error(`Discord webhook failed with HTTP ${response.status}: ${text}`)
  }
}

// ─── Main cycle ─────────────────────────────────────────────────────────────

export async function runReliabilityAlertCycle(
  options?: ReliabilityAlertCycleOptions
): Promise<ReliabilityAlertCycleResult> {
  const evaluation = await evaluateReliabilityAlerts(
    options?.windowMinutes,
    options?.baselineDays
  )
  const repeatMinutes =
    typeof options?.repeatMinutes === 'number' && Number.isFinite(options.repeatMinutes)
      ? Math.max(5, Math.floor(options.repeatMinutes))
      : 60
  const dryRun = options?.dryRun === true
  const githubToken = options?.githubToken ?? process.env.GITHUB_ALERT_TOKEN
  const githubRepo = options?.githubRepo ?? process.env.GITHUB_ALERT_REPO

  let states: Array<{
    alertKey: string
    isOpen: boolean
    lastNotifiedAt: Date | null
    githubIssueNumber: number | null
  }> = []
  let alertStatePersistenceAvailable = true

  try {
    states = await prisma.operationalAlertStates.findMany({
      where: { alertKey: { in: evaluation.rules.map((r) => r.alertKey) } },
      select: {
        alertKey: true,
        isOpen: true,
        lastNotifiedAt: true,
        githubIssueNumber: true,
      },
    })
  } catch (error) {
    if (!isMissingOperationalAlertStatesTableError(error)) throw error
    alertStatePersistenceAvailable = false
  }

  const stateMap = new Map(states.map((s) => [s.alertKey, s]))
  const triggered: ReliabilityAlertRuleStatus[] = []
  const resolved: ReliabilityAlertRuleStatus[] = []
  // Track the GitHub issue number per rule for Discord notification
  const issueNumbers = new Map<string, number | null>()

  if (!dryRun && alertStatePersistenceAvailable) {
    for (const rule of evaluation.rules) {
      const existing = stateMap.get(rule.alertKey)
      const numericValue =
        typeof rule.currentValue === 'number' && Number.isFinite(rule.currentValue)
          ? rule.currentValue
          : null

      if (rule.breached) {
        const isFirstTrigger = !existing?.isOpen
        const shouldNotify =
          isFirstTrigger || shouldNotifyAgain(existing.lastNotifiedAt ?? null, repeatMinutes)

        if (shouldNotify) triggered.push(rule)

        let issueNumber = existing?.githubIssueNumber ?? null

        // Create a GitHub issue on first trigger
        if (isFirstTrigger && githubToken && githubRepo) {
          const created = await createGitHubIssue({
            token: githubToken,
            repo: githubRepo,
            rule,
            runbookBaseUrl: options?.runbookBaseUrl,
            triggeredAt: evaluation.generatedAt,
          }).catch((err) => {
            logger.error('GitHub issue creation failed', { alertKey: rule.alertKey, err })
            return null
          })
          if (created !== null) issueNumber = created
        }

        issueNumbers.set(rule.alertKey, issueNumber)

        await prisma.operationalAlertStates.upsert({
          where: { alertKey: rule.alertKey },
          create: {
            alertKey: rule.alertKey,
            isOpen: true,
            lastValue: numericValue,
            lastTriggeredAt: new Date(),
            lastNotifiedAt: shouldNotify ? new Date() : null,
            githubIssueNumber: issueNumber,
          },
          update: {
            isOpen: true,
            lastValue: numericValue,
            lastTriggeredAt: new Date(),
            ...(shouldNotify ? { lastNotifiedAt: new Date() } : {}),
            ...(issueNumber !== null ? { githubIssueNumber: issueNumber } : {}),
          },
        })

        continue
      }

      if (existing?.isOpen) {
        resolved.push(rule)
        issueNumbers.set(rule.alertKey, existing.githubIssueNumber ?? null)

        // Close the GitHub issue on resolution
        if (existing.githubIssueNumber && githubToken && githubRepo) {
          await closeGitHubIssue({
            token: githubToken,
            repo: githubRepo,
            issueNumber: existing.githubIssueNumber,
            rule,
            resolvedAt: evaluation.generatedAt,
          }).catch((err) => {
            logger.error('GitHub issue closure failed', {
              alertKey: rule.alertKey,
              issueNumber: existing.githubIssueNumber,
              err,
            })
          })
        }

        await prisma.operationalAlertStates.update({
          where: { alertKey: rule.alertKey },
          data: {
            isOpen: false,
            lastValue: numericValue,
            lastResolvedAt: new Date(),
            githubIssueNumber: null,
          },
        })
      }
    }
  } else {
    for (const rule of evaluation.rules) {
      if (rule.breached) triggered.push(rule)
    }
  }

  if (!dryRun && !alertStatePersistenceAvailable) {
    logger.warn('OperationalAlertStates table is missing; alert dedupe/state persistence is disabled')
  }

  let notificationsSent = 0
  if (options?.webhookUrl) {
    for (const rule of triggered) {
      const embed = buildDiscordEmbed({
        status: 'TRIGGERED',
        rule,
        generatedAt: evaluation.generatedAt,
        runbookBaseUrl: options.runbookBaseUrl,
        githubIssueNumber: issueNumbers.get(rule.alertKey),
        githubRepo,
      })
      await sendDiscordEmbed(options.webhookUrl, embed)
      notificationsSent += 1
    }

    for (const rule of resolved) {
      const embed = buildDiscordEmbed({
        status: 'RESOLVED',
        rule,
        generatedAt: evaluation.generatedAt,
        runbookBaseUrl: options.runbookBaseUrl,
        githubIssueNumber: issueNumbers.get(rule.alertKey),
        githubRepo,
      })
      await sendDiscordEmbed(options.webhookUrl, embed)
      notificationsSent += 1
    }
  } else if (triggered.length > 0 || resolved.length > 0) {
    logger.warn('Reliability alerts changed state but webhook URL is not configured', {
      triggered: triggered.map((r) => r.alertKey),
      resolved: resolved.map((r) => r.alertKey),
    })
  }

  return { evaluation, triggered, resolved, notificationsSent, dryRun }
}
